# -*- coding: utf-8 -*-
"""Feature_scaling.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ggtgh1mRCGOxjmIFBpFA-Bfk1EpfFMUw
"""

#Label Encoder

import pandas as pd
from sklearn.preprocessing import LabelEncoder


data ={
    "Customer_id":[1,2,3,4,],
    "Ranks":["First","Second","Third","Fourth"],
    "frutis":["apple","bananna","orange","kivi"],
    "Gender":["Male","Female","Male","Female"]
}

df = pd.DataFrame(data)
print(f"The Data is :\n\n {df}\n")
label_encoder = LabelEncoder()
df["encoded_ranks"] = label_encoder.fit_transform(df["Ranks"])
df["encoded_frutis"] = label_encoder.fit_transform(df["frutis"])
print(f"The LabeleEncoded Data id :\n \n{df}\n")

import pandas as pd

from sklearn.preprocessing import OneHotEncoder

data ={
    "Customer_id":[1,2,3,4,],
    "Ranks":["First","Second","Third","Fourth"],
    "frutis":["apple","bananna","orange","kivi"],
    "Gender":["Male","Female","Male","Female"]
}

df = pd.DataFrame(data)
print(f"The Data is :\n\n {df}\n")
on_hot_encoder = OneHotEncoder()
column_encode = ['Gender','Ranks','frutis']

encoded_data = on_hot_encoder.fit_transform(df[column_encode])
encoded_columns = on_hot_encoder.get_feature_names_out(column_encode)

encoded_data_dense = encoded_data.toarray()
encoded_df = pd.DataFrame(encoded_data_dense, columns=encoded_columns)
df = pd.concat([df,encoded_df],axis=1)

print(f"The One Hot Encoder :\n\n {encoded_df}\n")

