# -*- coding: utf-8 -*-
"""Function.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WVx2Oy3etSxpANk8yS6hvLMYlyQytnj6
"""

def add(x,y):
  return x+y
result=add(3,4)
print(result)

result=lambda x,y:x+y
print(result(3,4))

result=lambda x,y:x*y
print(result(5,6))

#iterablel
lst=[1,2,3,4,5,6,7,8,9]
var_iter=iter(lst)
print(var_iter)

type(var_iter)

for i in var_iter:
  if i % 2==0:
    print(i)

#by using iter keyword check for number is <5 then add the 1 value and print the number

for i in var_iter:
  if i < 5:
    i+=1
    print(i)

ls=[1,2,3,4,56,]
var_iter=iter(ls)

for i in var_iter:
  if i < 5:
    i+=1
    print(i)

#generator
def square(i):
  for i in range(i):
    i = i+1
    return i
res = square(10)
print(res)

def square(i):
  for i in range(i):
    i = i+1
    yield i
square(10)
for i in square(10):
  print(i)

#genarator  using yield we can get all numbers by using return we will get the last number

def square(i):
  for i in range(i):
    i = i **2
    yield i
square(10)
for i in square(10):
  print(i)

